trigger: none


pool:
 name: App_Agent
 demands: Agent.Name -equals App_Agent_Server
  

stages:
  - stage: ci
    jobs:
      - job: linting_checking
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'stylelint "**/*.css"'
            workingDirectory: '$(System.DefaultWorkingDirectory)'