trigger: none


pool:
  name: App_Agent
  demands: Agent.Name -equals app_linux_agent


stages:
  - stage: javainstallation
    jobs:
      - job: javainstall
        steps:
        - task: JavaToolInstaller@1
          inputs:
            versionSpec: '8'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
