trigger: none


pool:
 name: App_Agent
 demands: Agent.Name -equals App_Agent_Server
  

stages:
  - stage: ci
    jobs:
      - job: linting_checking
        steps:
        - task: PowerShell@2
          displayName: stylelint_checking
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              npm install -g stylelint stylelint-config-standard stylelint-junit-formatter
              npx stylelint "src/main/webapp/**/*.css" --config "stylelint.config.mjs" --custom-formatter node_modules/stylelint-junit-formatter --output-file stylelint-report.xml

          