trigger: none


pool:
 name: App_Agent
 demands: Agent.Name -equals App_Agent_Server
  

stages:
  - stage: ci
    jobs:
      - job: linting_checking
        steps:
        - task: PowerShell@2
          displayName: stylelint_checking
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: |
              npm install -g stylelint stylelint-config-standard
              npx stylelint "src/main/webapp/**/*.css" --config "stylelint.config.mjs"

        - task: CmdLine@2
          inputs:
            script: '''biome lint $(System.DefaultWorkingDirectory) --reporter=junit > biomeresult.xml'''
            workingDirectory: '$(System.DefaultWorkingDirectory)'