trigger: none


pool:
  name: App_Agent
  demands: Agent.Name -equals app_linux_agent


stages:
  - stage: javainstallation
    jobs:
      - job: javainstall
        steps:
        - task: Bash@3
          displayName: install openjdk
          inputs:
            targetType: 'inline'
            script: |
              sudo apt update -y
              sudo apt install -y openjdk-17-jdk
              java -version
          
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              sudo apt install -y maven
              mvn -version

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'mvn clean package'
